"""The Assembler Agent - Information integration and formatting."""

from __future__ import annotations

import logging
from typing import Any

from src.agents.base import BaseAgent
from src.models.recommendation import (
    RecommendationCandidate,
    RecommendationCard,
    RecommendationResponse,
    ThemeLiteral,
    UserProfile,
)

logger = logging.getLogger(__name__)

THEME_TITLES: dict[ThemeLiteral, str] = {
    "books": "书籍",
    "games": "游戏",
    "movies": "电影",
    "anime": "动漫",
}


class AssemblerAgent(BaseAgent):
    """信息整合者，负责输出标准化推荐卡片。"""

    def __init__(self, *, theme: ThemeLiteral, **kwargs: Any) -> None:
        super().__init__(theme=theme, **kwargs)

    async def process(
        self,
        *,
        user_profile: UserProfile,
        candidates: list[RecommendationCandidate],
        summaries: dict[str, str],
        reasons: dict[str, str],
        intro_message: str,
    ) -> RecommendationResponse:
        """Assemble final recommendation response.

        Args:
            user_profile: Structured user profile
            candidates: Candidate list from selector
            summaries: Title -> summary map
            reasons: Title -> recommendation reason map
            intro_message: Friendly message generated by selector

        Returns:
            Recommendation response ready for API output
        """
        logger.info(
            "Assembler integrating %s candidates for theme=%s",
            len(candidates),
            self.theme,
        )

        cards: list[RecommendationCard] = []
        for candidate in candidates:
            summary = summaries.get(candidate.title)
            if not summary:
                logger.warning("Missing summary for %s", candidate.title)
                summary = self._default_summary(candidate)

            reason = reasons.get(candidate.title)
            if not reason:
                logger.warning("Missing recommendation reason for %s", candidate.title)
                reason = self._default_reason()

            cards.append(
                RecommendationCard(
                    title=candidate.title,
                    creator=candidate.creator,
                    metadata=candidate.metadata,
                    summary=summary,
                    reason=reason,
                )
            )

        message = self._compose_message(user_profile, len(cards), intro_message)

        response = RecommendationResponse(
            theme=self.theme,
            user_profile=user_profile,
            recommendations=cards,
            message=message,
            request_id="",  # Will be set by service layer
        )

        logger.info("Assembler successfully created recommendation response")
        return response

    def _default_summary(self, candidate: RecommendationCandidate) -> str:
        return (
            f"{candidate.title} 由 {candidate.creator} 创作，具备鲜明的主题特色，"
            "是该类别中值得体验的代表作品。"
        )

    def _default_reason(self) -> str:
        return "它与您的需求高度匹配，可以带来与众不同的体验。"

    def _compose_message(
        self, profile: UserProfile, count: int, intro: str
    ) -> str:
        label = THEME_TITLES.get(self.theme, "内容")
        summary = profile.summary or f"关于您最近对{label}的偏好"
        attributes_preview = ", ".join(
            f"{key}: {self._format_attribute(value)}"
            for key, value in list(profile.attributes.items())[:3]
        )

        core_message = (
            f"{summary}，我们基于这些偏好精选了 {count} 个{label}。"
            f"{'；' + attributes_preview if attributes_preview else ''}"
            "欢迎告诉我哪一个最打动你，或继续探索更多灵感。"
        )

        return f"{intro.strip()}\n\n{core_message}".strip()

    def _format_attribute(self, value: Any) -> str:
        if isinstance(value, list):
            return "、".join(str(item) for item in value)
        if isinstance(value, dict):
            return " | ".join(f"{k}:{v}" for k, v in value.items())
        return str(value)
